//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIA_Fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurement
    {
        public int measurementsID { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> bodyfatPercentage { get; set; }
        public string username { get; set; }
    
        public virtual User User { get; set; }
    }
}
