//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIA_Fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workout
    {
        public int workoutID { get; set; }
        public string type { get; set; }
        public Nullable<decimal> duration { get; set; }
        public Nullable<decimal> caloriesBurned { get; set; }
        public System.DateTime date { get; set; }
        public string username { get; set; }
    
        public virtual User User { get; set; }
    }
}
